dofile("internal/conf.lua")
process, chevrons, connection = sg.stargateState()
print("Process:", process)
print("Active Chevrons:", chevrons)
print("Connection:", connection)
print("Energy:", sg.energyAvailable())
print("Remote Address:", sg.remoteAddress())
print("Local Address:", sg.localAddress())
print("Iris State:", sg.irisState())